---
services:
  postgres:
    image: postgres
    container_name: gym
    restart: 'no'
    environment:
      POSTGRES_USER: ozzu
      POSTGRES_PASSWORD: marij
      POSTGRES_DB: gym
    ports:
      - '5432:5432'
    volumes:
      - gym_data:/var/lib/postgresql/data
    networks:
      - gym

  pgadmin:
    image: dpage/pgadmin4
    container_name: gym_pgadmin
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: ozzu@mari.net
      PGADMIN_DEFAULT_PASSWORD: marij
    ports:
      - '5050:80'
    networks:
      - gym
    depends_on:
      - postgres

networks:
  gym:
    driver: bridge

volumes:
  gym_data:
