---
services:
  postgres:
    image: postgres
    container_name: gym
    restart: 'no'
    environment:
      POSTGRES_USER: ozzu
      POSTGRES_PASSWORD: marij
      POSTGRES_DB: gym
    ports:
      - '5432:5432'
    volumes:
      - gym_data:/var/lib/postgresql/data
    networks:
      - gym

networks:
  gym:
    driver: bridge

volumes:
  gym_data:
